# Generated by Django 4.2.4 on 2023-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('reminder', models.CharField(choices=[('1', '1 hour'), ('2', '2 hour'), ('3', '4 hour'), ('4', '1 day'), ('5', '1 week')], max_length=255)),
            ],
        ),
    ]
