# Generated by Django 4.2.4 on 2023-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0002_remove_event_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
