# Generated by Django 4.2.4 on 2023-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0003_alter_event_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_date',
            field=models.DateTimeField(),
        ),
    ]
